Args = --enable-native-access=ALL-UNNAMED \
       --initialize-at-run-time=dev.ivchenko.webview.foreign.NativeLibraries,dev.ivchenko.webview.gtk.binding.GLib,dev.ivchenko.webview.gtk.binding.Gtk,dev.ivchenko.webview.gtk.binding.WebKit,dev.ivchenko.webview.gtk.GtkDispatcher,dev.ivchenko.webview.gtk.GtkWebviewBackend
